shieldproject/shield

src/plugin/dummy/dummy.go
src/plugin/endpoint.go
src/plugin/errors.go
src/plugin/plugins.go
vendor/manifest
vendor/src/github.com/mattn/go-shellwords/README.md
vendor/src/github.com/mattn/go-shellwords/shellwords.go
vendor/src/github.com/mattn/go-shellwords/shellwords_test.go
vendor/src/github.com/mattn/go-shellwords/util_posix.go
vendor/src/github.com/mattn/go-shellwords/util_windows.go

Added support for things plugins might need to do, like pull values from their ShieldEndpoint, and exec external utilities

Added exec support for plugins

---

api_agent/api_agent.go
api_agent/archives.go
api_agent/jobs.go
api_agent/plugins.go
api_agent/retention_policy.go
api_agent/schedule.go
api_agent/stores.go
api_agent/tasks.go
cmd/shield/archives_cli.go
cmd/shield/common_cli.go
cmd/shield/jobs_cli.go
cmd/shield/main.go
cmd/shield/plugins_cli.go
cmd/shield/retention_policies_cli.go
cmd/shield/schedules_cli.go
cmd/shield/stores_cli.go
cmd/shield/targets_cli.go
cmd/shield/tasks_cli.go

Refactored and added missing commands

Refactored and added missing commands

---

plugin/postgres/plugin.go

Force postgres plugin to use the psql provided by shield-boshrelease

---

db/schema.go
db/schema_v1.go

To modify schema, two steps are required.
First create a new schema_vX.go file,
where you define a new type implementing
the Schema interface. Next, add the schema
version + instantiation of the new type to
the Schemas map in schema.go

Enabled schema migrations

---

cmd/shield/main.go

Fail noisily for unrecognized subcommands

---

api/api.go

Drop trailing slash on SHIELD_TARGET env var

---

api/status.go
cmd/shield/main.go
supervisor/status_api.go
supervisor/status_api_test.go
supervisor/supervisor.go
version/version.go

New `shield status' command and matching /v1 endpoint

---

cmd/shield/main.go
cmd/shield/utils.go

Better support for --debug option

---

db/db.go
supervisor/supervisor.go

... and purge their archives.
Fixes #30

Fail Running Tasks on Startup

---

cmd/shield/main.go

I think this more explicitly states the desired behavior.

Clarifying Target IP in 'ls archives'

---

cmd/shield/command.go
cmd/shield/main.go

Output to terminal if the user hasn't specified either SHIELD_TARGET or used `shield -H`.

Checking for SHIELD_TARGET env var

---

cmd/shield/main.go

Newly created jobs are now unpaused by default

---

api/api.go
bin/bkp
cmd/shield/command.go
cmd/shield/main.go
share/setup

Better Shield CLI Help / Environment Variable Naming

---

timespec/lang.y
timespec/lexer.go
timespec/spec.go
timespec/timespec_test.go
timespec/util.go
timespec/y.go
timespec/y.output

The following timespecs are now recognized:
- hourly at quarter after
- hourly at :20
- every  hour at x:35
- every hour at 10 til
- etc.
Fixes #68

Hourly Timespecs

---

supervisor/supervisor.go

We apparently were not setting TimeoutAt (leaving it at the zero value
of "a long time ago" which was triggering the timeout logic immediately
after a task was kicked off (and transitioned from schedq to runq).
In addition, cancellation of a timed out task was not removing the task
from the runq, which was causing us to loop repeatedly trying to cancel
the same tasks over and over again.
Fixes #72

Fix Timeout Logic

---

db/tasks.go

Fixes issue #99 
Added a validation function to ensure that times that are <= 0 aren't used.

Added effective time validation

---

plugin/fs/plugin.go

The `fs` plugin can now be used as a store plugin, to store backup
archives on-disk.  It works similar to the S3 plugin in this regard, and
uses a date-based directory structure for all backups, with a UUID on
the archive file for uniqueness.

Implement "store" functionality for `fs` plugin

---

supervisor/worker.go

Clean up client connections instead of deferring

---

docs/api/http.md
supervisor/status_api.go
supervisor/supervisor.go

New API for better visibility into supervisor guts

---

supervisor/supervisor.go

Remove Tasks from runq when the complete or fail

---

cmd/shield/main.go

This ended up being a smaller change than I initially thought...

list backends now supports raw output

---

Godeps/Godeps.json
plugin/plugin.go
vendor/github.com/ErikDubbelboer/gspt/.gitignore
vendor/github.com/ErikDubbelboer/gspt/.travis.yml
vendor/github.com/ErikDubbelboer/gspt/LICENSE
vendor/github.com/ErikDubbelboer/gspt/Makefile
vendor/github.com/ErikDubbelboer/gspt/README.md
vendor/github.com/ErikDubbelboer/gspt/gspt.go
vendor/github.com/ErikDubbelboer/gspt/setproctitle.h

Fixes #166 
Triggers the name change on importing the `plugin` package.
```
./s3 -e '{ "secret_key":"secretkey" }'
```
```
→  ps -ef | grep s3
501 45789   743   0  9:56PM ttys002    0:00.00 grep s3
501 45787 43133   0  9:56PM ttys003    0:00.01 ./s3
```

hide yo creds, hide yo wife

---

cmd/shield/main.go
cmd/shield/utils.go

Fixes #171
Also added parameters to help dialogue for `create backend` and `backend`.

backend syntax and help

---

api/url.go

CLI Shouldn't Fail On POST Requests If User is Prompted For Auth

---

supervisor/archives_api_test.go

added tests around api responses when queuing restores

---

supervisor/supervisor.go
webui/js/app.js

Webui pretty json

---

api/jobs.go
api/retention_policy.go
api/schedule.go
api/targets.go
cmd/shield/finder.go
cmd/shield/main.go
db/jobs.go
db/retention.go
db/schedules.go
db/targets.go
supervisor/jobs_api.go
supervisor/jobs_api_test.go
supervisor/retention_api.go
supervisor/retention_api_test.go
supervisor/schedules_api.go
supervisor/schedules_api_test.go
supervisor/stores_api_test.go
supervisor/targets_api.go
supervisor/targets_api_test.go

also cli support and tests for api
Fixes #112

implemented exact name matching in API

---

bin/dev-setup
bin/testdev
db/archives.go
db/archives_test.go
supervisor/archives_api_test.go
webui/index.html
webui/js/app.js

Performed the following changes:
- Replaced the restore icon with a button
- Added a confirmation popup when performing a restore
- Fix for token for setting up local development env

Restore button UI change

---

plugin/mysql/plugin.go

This adds a more generic implementation of #236.
This commit adds support for mysqldump options in the mysql plugin.
The setting "mysql_options" allows setting common mysqldump options
like --force and/or --single-transaction.
This gives the MySQL Admins more power on how shield runs the
backup.
If the database contains VIEWS which are invalid, mysqldump will
exit with an error and the backup will fail. Adding --force will
make mysqldump ignore the error and create a proper backup (altough
the DB is probably not in the best state, but things usually won’t
get better when backuping ... )

Add support for mysqldump options in mysql plugin

---

plugin/s3/plugin.go

S3 plugin: don't use a default port

---

ci/release_notes.md
db/jobs.go
docs/api/http.md
supervisor/status_api.go
webui/index.html
webui/js/app.js

- An API endpoint `v1/status/jobs` was added to show the most recent success or failure of a job task.  Intended for a monitoring/alerting application to scrape this information periodically
- In GUI, under Jobs the status is now color coded
- Also on the dashboard recently failed jobs will appear in a notification bar at the top

Job Status Enhancements

---

README.md

This link now works as expected on github

Fix path to dummy/example plugin

---

.gitignore
Godeps/Godeps.json
Makefile
plugin/swift/plugin.go
vendor/git.openstack.org/openstack/golang-client/LICENSE
vendor/git.openstack.org/openstack/golang-client/objectstorage/v1/objectstorage.go
vendor/git.openstack.org/openstack/golang-client/openstack/README.md
vendor/git.openstack.org/openstack/golang-client/openstack/auth-password.go
vendor/git.openstack.org/openstack/golang-client/openstack/auth-token.go
vendor/git.openstack.org/openstack/golang-client/openstack/auth.go
vendor/git.openstack.org/openstack/golang-client/openstack/service-catalog.go
vendor/git.openstack.org/openstack/golang-client/openstack/session.go
vendor/git.openstack.org/openstack/golang-client/util/rfc8601DateTime.go
vendor/git.openstack.org/openstack/golang-client/util/util.go

To dev/test this via `./bin/dev-setup`, replace:
```
echo "store=$store"
```
with:
```
store=$( $shieldcomm create store <<MEEP1 | $jqcomm .uuid
{
"endpoint": "{\"auth_url\":\"https://identity.api.rackspacecloud.com/v2.0\",\"project_name\":\"xxx\",\"username\":\"xxx\",\"password\":\"xxx\",\"container\":\"bucket\",\"debug\":false}",
"name": "DevSwift",
"plugin": "swift",
"summary": "Rackspace Swift objectstorage"
}
MEEP1 )
echo "store=$store"
```

[swift] New store plugin 'swift': for OpenStack Swift/Rackspace Cloud Files

---

plugin/mongo/plugin.go

Hey all,
We run Mongo with SSL enabled, but the mongo plugin does not have the ability to pass the `--ssl` flag to the mongo commands. Rather than add a flag specific to `ssl` we followed the example from the [mysql plugin](https://github.com/starkandwayne/shield/blob/master/plugin/mysql/plugin.go#L27) and added the `options` parameter that allows passing any flags.
#ultimatesoftware

Add the ability to pass generic mongo options

---

tui/report.go
tui/table.go
tui/tui_test.go

tui can handle non-printing characters in tables

---

bin/testdev
core/auth.go
core/uaa_auth.go
dev/uaa.md
dev/uaa.yml
lib/uaa/uaa.go

This commit introduces a new Authentication Provider for SHIELD that
handles UAA as an OAuth2 backend, and maps to tenants based on a
combination of SHIELD configuration and granted SCIM rights in UAA.

UAA Authentication Provider

---

bin/testdev
core/api.go
core/auth.go
core/core.go
core/health.go
core/session.go
db/sessions.go
web2/htdocs/index.html

New UI necessary for doing SHIELD core initialization and unlock work.

Init and Unlock Screens

---

api/access.go
cmd/shield/commands/access/rekey.go
cmd/shield/commands/access/rotate.go
cmd/shield/main.go
core/api.go
crypter/vault.go
web2/htdocs/index.html

Implementation in place for key rotation via API, CLI or UI
Could probably use more CSS styling before final release

Encryption Key Rotation

---

core/api.go
core/auth.go
core/v2.go
route/request.go
web2/htdocs/index.html

In preparation for CLI support

Localauth API and Web UI changes

---

api/archives.go
cmd/shield/commands/archives/get.go
cmd/shield/commands/archives/list.go
core/core.go
db/archives.go
db/tasks.go
db/tasks_test.go
plugin/azure/plugin.go
plugin/consul-snapshot/plugin.go
plugin/consul/plugin.go
plugin/docker-postgres/plugin.go
plugin/dummy/dummy.go
plugin/fs/plugin.go
plugin/google/plugin.go
plugin/mock/mock.go
plugin/mongo/plugin.go
plugin/mysql/plugin.go
plugin/plugin.go
plugin/postgres/plugin.go
plugin/rabbitmq-broker/plugin.go
plugin/redis-broker/plugin.go
plugin/s3/plugin.go
plugin/scality/plugin.go
plugin/swift/plugin.go
plugin/xtrabackup/plugin.go

All plugins except GCP and Dummy now report size of archives via CLI and API

 Implemented tracking of archive size

---

api/access.go
api/errors.go
api/providers.go
api/status.go
api/url.go
bin/testdev
cmd/shield/commands/access/login.go
cmd/shield/commands/info/usage.go
cmd/shield/commands/options.go
cmd/shield/main.go
core/auth.go
core/token_auth.go
core/v2.go
route/request.go
route/route.go

Token auth cli

---

core/health.go
core/storage.go
core/v2.go
db/schema_v4.go
db/stores.go
db/tenants.go
web2/htdocs/index.html
web2/htdocs/js/lib.js

Added storage threshold functionality to the DB, API, and webUI
Altered archive_count to just be an int everywhere (int32 archives should be more than enough)
Pulled out Forecasting/Predicted implementation for now on webUI

Support for storage thresholds

---

bin/testdev
core/auth.go
core/config.go
core/core.go
core/session.go
core/storage.go
db/sessions.go
web2/htdocs/index.html
web2/htdocs/js/lib.js

Added automatic purging of expired sessions in slowloop and check on access to ensure session is valid
Updated webUI to better handle 401/403s in most cases.

Session timeouts

---

core/auth.go
core/v2.go
web2/htdocs/index.html

Added UI for management of invitation/banishment for tenant admins who are not necessarily site admins

Non SiteAdmin Tenant Management

---

db/db.go
db/db_test.go

The sqlite database connection is now protected with a global lock,
which will serialize concurrent readers AND writers, ensuring that only
one thread / goroutine is using the database connection at any single
point in time.  On agressively-scheduled SHIELDs (like testdev), this
avoids `database is locked.` errors from the SQLite3 driver, without
resorting to WAL logging or similar controls.

Global Database Lock

---

.gitignore
Makefile
plugin/webdav/plugin.go
t/plugins

The new `webdav` plugin allows archives to be stored to and retrieved
from an HTTP WebDAV server, like nginx with large disks.

New WebDAV plugin

---

core/v2.go
web2/htdocs/index.html

if you are not in a tenant and do not have a system role you will not see the hud, and if you attempt to ping the health endpoints without auth you will be rejected

added auth checks on health endpoints

---

plugin/mysql/plugin.go

At Orange FR, we backup our MySQL instances via the mysql plugin, with the following target configuration: `"mysql_options": "--flush-logs --add-drop-database --single-transaction  --opt"` and `mysql_database` left unspecified (empty). With these settings, SHIELD performs a MySQL backup of type FULL.
The problem is that a direct restore of such a backup is not possible with SHIELD.
```
	ERROR 1580 (HY000) at line 1: You cannot 'DROP' a log table
```
```
	Can't create table mysql.db (errno: -1 "Internal error < 0 (Not system error)"
```
To restore our instance, we must proceed in three steps
1. Modify the following parameters of the instance
```
set global enforce_storage_engine=NULL;
set global general_log=OFF;
set global slow_query_log=OFF
```
2. Start full restore with SHIELD
3. Set …

Improve backup and restore procedures in mysql plugin

---

core/core.go
crypter/vault.go

Vault now closes all connections after each request
In the future a more intelligent heartbeat system may need to be implemented.

Vault FD Leak Hotfix

---

plugin/xtrabackup/plugin.go

At Orange FR, we backup our MySQL instances via the xtrabackup plugin. It's working properly. But when the backup or the restore fail, we have no trace of the error in the logfile. 
In this PR work, we suggest to make some preliminary tests and to indicate in the log file the result of these tests.
For the backup, we test the existence of the backup temporary directory.
For the restore, we test 
- that the target Mysql instance is stopped
- the existence of the backup temporary directory
- the existence of the MySQL data directory
- and that the MySQL data directory is empty
Also, at the end of restore, we assign the uid-gid couple of the MySQL data directory to the contents of this directory
Don't hesitate to suggest any improvements to this work!
Cheers

Improve backup and restore procedures in xtrabackup plugin

---

plugin/cassandra/plugin.go
plugins

Hi folks,
Here is an Orange FR contribution for a Cassandra target plugin. This was successfully tested with our Work-In-Progress [cassandra release](https://github.com/orange-cloudfoundry/cassandra-cf-service-boshrelease).
Don't hesitate to make any feedback or comments and we'll improve the code and documentation in any way you may find relevant!
Cheers,
Benjamin GANDON

Orange contribution for a Cassandra target plugin

---

core/v2.go

Previously the websocket broadcasted the `Event` data as-is. However, this did not align with the changes made to the `/systems/` API responses. This commit adds functionality to serialize the `Event` data the same way `/systems/` does, which fixes some web UI bugs that relate to running tasks from `/systems/`.

Change websocket events data stucture to align with v2 systems

---

plugin/mysql/plugin.go

Skip the binary logging on MySQL backups

---

plugin/postgres/plugin.go

This commit adds two fields (host, port) for specifying a particular node to use when backing up a Postgres cluster. When restoring, the master IP is still used.
The following fields were added as optional inputs in the JSON:
```
"pg_read_replica_host" : "hostname of pg read replica",
"pg_read_replica_port" : "port of pg read replica",
```
Which, when both defined, override the original connection information when conducting a backup. Note that we assume the same credentials are used for both the nodes.

Add ability for Postgres plugin to backup via readonly node

---

plugin/s3/plugin.go

As talked about with Geoff Franks. This pull request adds Instance Profile authentication support, as an alternative to key and secret authentication.
Signed-off-by: David Bishop <dbisj@allstate.com>
Should pass Travis build now that go-s3 has been updated.

Added Amazon Instance Profiles authentication support

---

web2/htdocs/index.html

Fixes https://trello.com/c/M6KTEv2D

Fixes mislabeling of scheduled jobs

---

web2/htdocs/index.html
web2/htdocs/shield.css

Fixes https://trello.com/c/gKxTo3fO

Fixes missing notes on tasks

---

bin/testdev

add vault version `0.10.*` to allow running `make dev`

vault 0.10.* in dev/testdev

---

plugin/s3/plugin.go

This makes life easier on some S3 work-alikes, which can require that
S3 operations be given region names that do _not_ correspond to those
used by AWS itself.
Fixes #465

Make S3 region configurable

---

web/htdocs/index.html
web/htdocs/js/events.js
web/htdocs/js/shield.js

This PR is to add the functionality of allowing SHIELD admins to delete local users and to adds user password management.

Give Admins the ability to delete local users and change local user passwords

---

bin/shield-recover
ci/release_notes.md
core/api_v2.go
core/core.go
t/api

Adding in configurable plugin paths to core to be able to leverage the fs plugin for recovering shield itself.

Fix for shield-recover

---

ci/release_notes.md
cmd/shield/main.go

Support short UUIDs in restore- / purge-archive

---

ci/release_notes.md

Release notes added for CI/CD pipelines.

etcd release notes

---

.gitignore

ignore etcd binary

---

db/schema_v10.go

Handle same last_seen_at in v10 cleanup

---

db/bus.go
db/bus_test.go

Updated tests for bus event messages. It now covers tests for Agent, Job, Store, Target, Tenant, Task and Archive.

Mbus tests

---

db/bus.go
db/memberships.go
web/htdocs/index.html
web/htdocs/js/data.js
web/htdocs/js/events.js
web/htdocs/js/shield.js

Web UI now updates when tenant membership or role changes #610

Updated web UI code

---

db/agents.go

Modified agent struct to support mbus messages for metadata and sending an agent object update when agent status changes. Fixes #597

Changes to agent event handling

---

web/htdocs/js/data.js

Updated AEGIS code so that job status updates in real time which in turn updates the Data System Status. Fixes #503

Data system status

---

core/bus/bus.go
core/core.go
core/main.go
core/metrics/exporter.go
db/agents.go
db/tenants.go

Base code for Prometheus exporter

Prometheus exporter

---

core/api_v2.go
core/bus/bus.go
core/scheduler/chore.go
db/bus.go
db/jobs.go
db/schema_v1.go
db/schema_v4.go
db/schema_v5.go
db/schema_v6.go
db/stores.go
db/targets.go
db/tasks.go
web/htdocs/js/data.js

Implemented new health status messages for targets, stores and jobs

New mbus health event

---

db/jobs.go
db/schema.go
db/schema_test.go
db/schema_v11.go
db/schema_v12.go

This pr should fix #653, #654 and #656 . I tested the database migration locally by using the code from 8.5.0 and then upgrading it and it works fine.

Fix database migrations to v11

---

plugin/fs/plugin.go

This was causing a considerable amount of log output which, given our
current architecture, is bringing the SHIELD core to its knees. Not only
does this cause fs jobs to take an extremely long amount of time to
complete (see, 4 days instead of 30 minutes), but it brings the rest of
SHIELD to its knees. This is because all this logging causes a massive
amount of database writes, leading to much lock contention.

fs plugin - Only print every file name if requested

---

web/htdocs/js/events.js

Case insensitive web UI sorting

---

db/bus_test.go

Updated mbus tests to reflect health-update event.

Mbus-tests

---

Dockerfile
docker-compose.yml

Updated docker-compose and dockerfile

SHIELD docker images

---

docs/ops/plugins.md

Updated documentation for the new **metashield** plugin

Metashield documentation

---

plugin/s3/plugin.go

Similar to the 8051b28 commit, this commit will attempt the requests
without the path-based addressing in the Purging task.
Fixes #568

Handle AWS 301's in Purge task (#569)

---

core/vault/client.go
go.mod
go.sum

Populate root token on shield unlock and also force unlock if root token unknown

Vault-kv fix

---

core/vault/client.go

This would behave poorly if shieldd had been restarted but not Vault - the Vault would not be uninitialized or sealed, so the health check wouldn't return an error, and so the function would return Ready. But we actually wouldn't have a token yet, so backups would fail.
I had screwed up the ordering when I tried to fix the previous ordering, which would check for token validity before checking for vault seal/uninit status.
To validate that this works, it needs to be tested that the unseals and backs up as expected
1. on a clean install
2. after a restart of both vault and shield
3. after a restart of just shield
4. after a restart of just vault

fix ordering of vault status checks even more
