Godeps/Godeps.json
Godeps/_workspace/src/gopkg.in/yaml.v2/LICENSE
Godeps/_workspace/src/gopkg.in/yaml.v2/LICENSE.libyaml
Godeps/_workspace/src/gopkg.in/yaml.v2/README.md
Godeps/_workspace/src/gopkg.in/yaml.v2/apic.go
Godeps/_workspace/src/gopkg.in/yaml.v2/decode.go
Godeps/_workspace/src/gopkg.in/yaml.v2/decode_test.go
Godeps/_workspace/src/gopkg.in/yaml.v2/emitterc.go
Godeps/_workspace/src/gopkg.in/yaml.v2/encode.go
Godeps/_workspace/src/gopkg.in/yaml.v2/encode_test.go
Godeps/_workspace/src/gopkg.in/yaml.v2/parserc.go
Godeps/_workspace/src/gopkg.in/yaml.v2/readerc.go
Godeps/_workspace/src/gopkg.in/yaml.v2/resolve.go
Godeps/_workspace/src/gopkg.in/yaml.v2/scannerc.go
Godeps/_workspace/src/gopkg.in/yaml.v2/sorter.go
Godeps/_workspace/src/gopkg.in/yaml.v2/suite_test.go
Godeps/_workspace/src/gopkg.in/yaml.v2/writerc.go
Godeps/_workspace/src/gopkg.in/yaml.v2/yaml.go
Godeps/_workspace/src/gopkg.in/yaml.v2/yamlh.go
Godeps/_workspace/src/gopkg.in/yaml.v2/yamlprivateh.go
bin/shield-pipe
supervisor/supervisor.go
supervisor/supervisor_suite_test.go
supervisor/supervisor_test.go
supervisor/task.go

Push the pipeline of co-processes into a Bash script that can handle the
race conditions, and thereby work around the Go runtime issue.  Notes in
bin/shield-pipe explain why.

Better Exec support in Go

---

api/url.go
cmd/shield/command.go
cmd/shield/main.go

- If there is JSON, try to decode it, but return an error anyway.
- If there is no JSON, return the error
- In the front-end, display those errors
Execute() and Invoke() got merged, because the second return val from
Execute() was pointless (bool ok - I found the command!), and once that
was removed, the funcs were identical.

Treat non-200 responses as errors in CLI

---

supervisor/archives_api.go
supervisor/archives_api_test.go
supervisor/jobs_api.go
supervisor/meta_api.go
supervisor/ping_api.go
supervisor/ping_api_test.go
supervisor/retention_api.go
supervisor/schedules_api.go
supervisor/status_api.go
supervisor/status_api_test.go
supervisor/stores_api.go
supervisor/supervisor_test.go
supervisor/targets_api.go
supervisor/tasks_api.go

HTTP 415 is for unsupported media types, which has nothing to do with
unimplemented endpoints.  Why I ever thought 415 was the right code is
beyond me.  Fixes #47

Use HTTP 501 (Not Implemented) instead of HTTP 415

---

cmd/shield/main.go

Also, define `shield help`
Fixes #52

Show `shield help` by default

---

cmd/shield/main.go
cmd/shield/utils.go

Use encoding/json for the JSON, not fmt.Sprintf.
Commonify the logic for generating the current username.
Fix 'restore-to-target' functionality to track user.
Fix 'restore-to-target' to not barf up bad (non-)JSON payloads.
Fix 'restore-to-target' functionality to use the right options.
Fixes #64

Better Request Payload Handling

---

cmd/shield/command.go
cmd/shield/finder.go
cmd/shield/main.go

Fixes #65
`shield restore` now searches through jobs, and then shows you the
archives for that job, that can be restored.

Make `restore' UX better

---

db/tasks.go
db/tasks_test.go
supervisor/supervisor.go
supervisor/worker.go

See commit messages for details

Failure detection fixes

---

cmd/shield/main.go
cmd/shield/utils.go
tui/table.go
tui/tui_suite_test.go
tui/tui_test.go

The tui.Table type is now backed by a transparent tui.Grid, which correctly handles multi-line strings at the cell level, to provide the correct whitespace padding in the gaps between columns and rows.  This allows us to switch over to output with manual line breaks to get better table output.
The original intent of #36 was to find a good word-wrapping algorithm, but given UUIDs, datestamps and JSON output, even if we _could_ find an optimal layout, it would only work for the computer, not the human operators.  Hence, this compromise.
Also, I added a commit that introduces a utility function, `PrettyJSON(string)` that takes a string, unmarshals it, re-marshals it with 2-space indenting, and returns the multiline string as a result.  This should clean up our listing table output nicely.

Better Tabular Display

---

supervisor/worker.go

Added `StoppedAt: time.Now()` to the `updates` channel information when the dial fails.

Update task StoppedAt timestamp when failing to connect to an Agent

---

api/tasks.go
db/tasks.go
db/tasks_test.go

Filter works in conjunction with `ForStatus` filter - so can see X most recent tasks or e.g. X most recent running tasks.
Fixes issue #101

Added `?limit=:n` parameter to API to limit how many tasks to output

---

db/tasks_test.go
supervisor/tasks_api.go
supervisor/tasks_api_test.go

API prevents non-integer values and values <= 0 from being passed as limits.
Fixes #103

Prevents invalid tasks?limit values

---

api/archives.go
cmd/shield/command.go
cmd/shield/main.go
db/archives.go
db/archives_test.go
supervisor/archives_api.go
supervisor/archives_api_test.go
supervisor/tasks_api.go
supervisor/util_api.go

Similar to tasks, the number of archives listed can now be limited with "limit" and the CLI uses 20 as the default.
Fixes #81

Limits number of archives listed to 20 by default

---

plugin/mysql/plugin.go

Allow users to specify a database to back up via the `mysql`
plugin, optionally. If not specified, the plugin will resort
to backing up all databases the user has access to. To specify
the database, the `mysql_database` key has been added to the
endpoint configuration.

Allow targeting of mysql backups to specific databases.

---

plugin/docker-postgres/plugin.go
plugin/dummy/dummy.go
plugin/elasticsearch/plugin.go
plugin/fs/plugin.go
plugin/mysql/plugin.go
plugin/plugin.go
plugin/plugin_test.go
plugin/postgres/plugin.go
plugin/rabbitmq-broker/plugin.go
plugin/redis-broker/plugin.go
plugin/s3/plugin.go

SHIELD plugins now have a new mode to support, `validate`, which is
repsonsible for reading a SHIELD endpoint and verifying that the
required parameters are present.  Plugins may opt to perform whatever
validations they see fit, including basic presence checks to more
in-depth value assertions (i.e. S3's signature_version must be either 2
or 4).
Each compiled plugin can now be told to run the `validate` subcommand
which will trigger this new behavior, print (hopefully helpful)
information to the screen, and exit 0 if the endpoint is valid.
All built-in plugins have been updated to perform the necessary checks,
based on existing logic.

Plugin Validation Mode

---

timespec/spec.go
timespec/timespec_test.go

This commit addresses a rather common scheduling scenario with weekly
backups that will send SHIELD into a fit of constant job re-execution.
The Next() logic for weekly Spec objects doesn't properly advance to the
next week if the current day lands on the same weekday as the "next"
day.
In practice, this happens all the time, since the scheduler calculates
the Next() value immediately after the scheduled execution time (on the
same day).  The observed phenomenon is that the suervisor will keeping
seeing the "next" run time of a weekly job as "earlier today", until the
midnight boundary causes the buggy logic to forward to the next week.
This has been fixed, and regression tests added.

Fix Weekly Timespec Bug

---

plugin/endpoint.go
plugin/fs/plugin.go
plugin/mysql/plugin.go
plugin/postgres/plugin.go
plugin/rabbitmq-broker/plugin.go
plugin/s3/plugin.go

The following plugin endpoints have changed:
- fs: `bsdtar` is a new optional parameter to override the default,
BOSH-based path to the tar binary.
- mysql: The `mysql_port` parameter now defaults to "3306"
- postgres: The `pg_port` parameter now defaults to "5432"
- rabbitmq-broker: The `skip_ssl_validation` parameter now defaults to
false (that is, validate SSL certificates)
- s3: The `signature_version` parameter now defaults to "4"
- s3: The `skip_ssl_validation` parameter now defaults to false (i.e.
validate SSL certificates)

Plugin Endpoint Default Values

---

agent/test/bin/big_dummy
agent/test/bin/dummy
bin/shield-pipe

Before we try to run the plugins in a pipeline, shield-pipe will now
validate the endpoint configurations for each plugin involved, and bail
out if any of them are invalid.
Also, cleaned up some output so that task logs are prettier.

shield-pipe: Run `validate` on all executed plugins

---

cmd/shield/forms.go
cmd/shield/main.go

Completes #76 
```
Retention Timeframe, in days: 65d
```
is now
```
Retention Timeframe, in days: 65
```
because redundancy.
Also, fixed a problem where `edit policy` was calculating default values incorrectly - namely, it was defaulting to 86,400 times whatever the previous value was. More days =/= better policy.

Reformatted retention policy cmds

---

Godeps/Godeps.json
supervisor/config.go
supervisor/config_test.go
supervisor/jwt.go
supervisor/jwt_test.go
supervisor/oauth.go
supervisor/oauth_test.go
supervisor/oauth_verifiers.go
supervisor/oauth_verifiers_test.go
supervisor/supervisor_test.go
supervisor/test/etc/oauth-ssl-checking.yml
supervisor/test/etc/oauth-ssl-skip-checking.yml
supervisor/webserver.go
vendor/github.com/geofffranks/botta/LICENSE
vendor/github.com/geofffranks/botta/README.md
vendor/github.com/geofffranks/botta/TODO
vendor/github.com/geofffranks/botta/http.go
vendor/github.com/geofffranks/botta/response.go
vendor/github.com/jhunt/tree/README.md
vendor/github.com/jhunt/tree/cursor.go
vendor/github.com/jhunt/tree/err.go
vendor/github.com/jhunt/tree/find.go
vendor/github.com/jhunt/tree/tree.go
vendor/github.com/markbates/goth/providers/cloudfoundry/cf.go
vendor/github.com/markbates/goth/providers/cloudfoundry/session.go

Added support for the UAA to be used as an OAauth2 provider
for SHIELD, to handle authentication/authorization. If used,
you must specify the `auth.oauth.provider_url` configuration property,
to point at the UAA being used.
Authorization is performed by seeing if the authenticated user is
in a member of a UAA group(s) listed in `auth.oauth.authorization.orgs`.

Enable UAA authentication/authorization support

---

api/api.go
api/config.go

The api.Config object now has a SecureEndpoint() method that will
attempt to determine the final scheme/host/port in use by SHIED (after
redirection), and use that directly.  This fixes #151, without exposing
sensitive tokens / basic-auth credentials over cleartext channels.
The extra hit against /v1/ping (to trigger server-side redirection that
not even SHIELD may be aware of) only occurs once, because
SecureEndpoint is memoized on the api.Config object.

Determine Secure URL via /v1/ping

---

.gitignore
plugin/postgres/plugin.go

**Changes**
- In configuration, a field `pg_database` was added as an option. If included, it will backup and run a `pg_dump` on the database specified in the `pg_database` key. If excluded or left as `""`, then Shield will run a `pg_dumpall` as before.
**Internally Changed**
- Postgres Plugin for a Target

Postgres Plugin Option of Specific Database

---

timespec/spec.go
timespec/timespec_test.go

This commit fixes a bug in the weekly scheduling behavior of
timespec.Spec objects.  A weekly schedule for 3am UTC on Sunday would
kick off at exactly 03:00:00 UTC.  The supervisor would then reschedule
the job for 03:00:00 UTC (the bug). Then, the supervisor would tick
once, and at 03:00:01+0000 (1s later) the supervisor would kick off
another task for the backup job, and reschedule the job (again) for
03:00:00 UTC.
This would continue until 03:01:00 UTC, at which point the scheduling
logic would work past the bug, see that the original spec timestamp is
in the past, and forward it one week.
The upshot of this is that for weekly backups, you get 60 copies of your
backups.  For redundancy?
Fixes #159, by checking if the timespec represents the current time
(to 1 second of precision), or …

Proper Weekly Re-scheduling

---

plugin/postgres/plugin.go

- Fixes  a bug where a Postgres dump file with a line longer than 64K could not be read by the scanner in the Postgres restore plugin.
- The plugin now returns non-0 codes on errors related to reading the file in.
- Fixed an off-by-one error in the debug logs when it says how many lines were in the dump file that was restored.

Fixes Postgres Restore Bug

---

api/archives.go
api/jobs.go
cmd/shield/main.go
db/tasks.go
supervisor/archives_api.go
supervisor/jobs_api.go
supervisor/jobs_api_test.go
supervisor/supervisor.go

The daemon now returns a task uuid for adhoc tasks (`run job` and `restore archive`).
The CLI will display these if the backend supports it.

Adhoc task uuid

---

supervisor/supervisor.go

I am getting 
```
--$ curl -XPOST  -H "X-Shield-Token: LETMEIN"  http://localhost:8181/v1/archive/58831f9a-1b02-4231-ab92-13e6adfacb47/restore
{"error":"a631f230-e68e-4766-82b3-9915a8b2b449"}
```
but the task id is valid and the job is finished.

correct a small bug during a post restore call

---

bin/dev-setup
plugin/fs/plugin.go

So, dev-setup shouldn't back up the working db because its annoying in the test environment when you lose archive records every time you restore.
To do this, the --exclude functionality of the fs plugin had to be fixed, because it was previously backing up ONLY the thing you wanted to not back up at all.

dev-setup excludes db. fs plugin exclude works

---

bin/testdev

default will be sqlite3
use DATABASE_TYPE to specify database driver
use DATABASE_DSN to specify data source name

allow testdev script to use different db backends

---

db/tasks.go
db/tasks_test.go
supervisor/supervisor.go

This is an attempt to fix #200 
Since task scheduling is not done in parallel, we can check prior to
starting a task whether it is allowed to run that task.
A task may not run if a task with same target uuid is running. This is
useful if a restore operation is currently in progress and another
backup should be initiated.

allow only a single task per target

---

ci/release_notes.md
db/tasks.go

With db backend MySQL/MariaDB the default values for the columns
target_plugin and target_endpoint won't be set. When we create a task
entry, we have to initialize the columns target_plugin and
target_endpoint with an empty string.

fix db sql statement to create purge task #205

---

plugin/fs/plugin.go

The `fs` target plugin stores its backup into the `/dev/st0` file (the bsdtar default) instead of `/dev/stdout`, as expected by SHIELDS.
As a result, the files in `{base_dir}/yyyy/mm/dd/HH/MM/SS/<uuid>` are always 14 bytes long bzip2 files (which actually encode an empty content).
There's a workaround for this issue, which is to set a `bsdtar: /var/vcap/packages/bsdtar/bin/bsdtar -f /dev/stdout` config for the `fs` target plugin.
In this PR, I submit a permanent fix.

Fixed `fs` target plugin output to `/dev/stdout` as expected

---

.gitignore
Makefile
ci/release_notes.md
ci/scripts/shipit
cmd/shield-agent/main.go
cmd/shield-schema/main.go
cmd/shield/main.go
cmd/shieldd/main.go

The new `make release` target handles cross-compilation of all server
components, including the plugins, server daemons and utilities, and the
static assets for the web UI.
Fixes #217

Binary Server Release Support

---

bin/shield-pipe
ci/release_notes.md

Fixes #215
These modifications to shield-pipe correctly detect the case where a
plugin is not sending data to the other side.  For backup operations,
this catches bad backups.  The restore-side is dubious, but applying the
patch there as well makes for some nice symmetry, and shouldn't hurt
anything.
The `head -c1` command grabs up to the first byte out of the stream and
writes it to a temporary file.  This should help us to keep the disk
impact as alow as possible, but it does mean that we know rely on disk
to be writable (at least `/tmp`)
cc @geofffranks 
Please don't merge this until Geoff has had a chance to review in light of #215

Bail out if no data is received by shield-pipe

---

cmd/shield/command.go
cmd/shield/main.go

Shifted old canon names to aliases. shield help contains a deprecation message.
command list now:
```
→  ./shield commands
NAME:
shield        CLI for interacting with the Shield API.
USAGE:
shield [options] <command>
ENVIRONMENT VARIABLES:
SHIELD_TRACE        set to 'true' for trace output.
SHIELD_DEBUG        set to 'true' for debug output.
COMMANDS:
INFO:
help              Get detailed help with a specific command
commands          Show the list of available commands
flags             Show the list of all command line flags
status            Query the SHIELD backup server for its status and version info
BACKENDS:
backends          List configured SHIELD backends
create-backend    Create or modify a SHIELD backend
backend           Select a particular backend for use
TARGETS:
targets …
```

Changed cli canon names

---

plugin/s3/plugin.go

Minio server doesn't deduplicate extra slash when putting object. (https://github.com/minio/minio/issues/3256)
Shield also expect leading slash to know where object is stored

Remove leading slash before storing

---

plugin/postgres/plugin.go

When backing up one database the postgres plugin will restore that to the database with the name `postgres` even if the database name was something different.
When performing a backup of all databases this bug does not show up.
This fixes issue #209

fix postgres single database backup bug

---

cmd/shield/main.go

After running `create-*` commands you would receive a message:
`The alias show target is deprecated in favor of target`
I made sure we were using the latest `show/list` commands after we created a new policy, schedule, target, store, etc.

remove usage of deprecated commands after creating new things

---

plugin/mysql/plugin.go

If you are running the mysql plugin right now you are forced to put the plugin in `/var/vcap/packages/shield-mysql/bin/` 
The postgres plugin allows you to specify a binary directory, so I added that feature to the mysql plugin.
If left undefined it defaults to `/var/vcap/packages/shield-mysql/bin/` this change will not break existing implementations.

Make mysql binary directory configurable

---

cmd/shield/main.go

This had already been fixed for `create-` commands. Just extending the fix to `edit-` as well.

Fixed deprecation message about show... when editing things.

---

cmd/shield/main.go

Hi guys,
The `shield help restore` was incomplete and actually misleading about the way `shield restore` was supposed to be used.
What I did here in this PR is document the normal (non `--raw`) mode for the `shield restore` to be clearer.
Cheers

Document the normal (non raw) mode for 'shield restore' cli

---

api/api.go
api/archives.go
api/jobs.go
api/retention_policy.go
api/schedule.go
api/status.go
api/stores.go
api/targets.go
api/tasks.go

When using the API library I want to trap the errors (even when there's no connection to the backend). The actual behavior is just to exit with a return code 1. This PR modifies this behavior to return the error instead of exiting.

Return an error instead of exiting when using the API ShieldURI function

---

api/status.go

PR https://github.com/starkandwayne/shield/pull/271 introduced a Job Status API endpoint (`/v1/status/jobs`), but the API library does not implement any function to fetch this endpoint. This PR adds a `GetJobsStatus` API function.

Add GetJobsStatus API function

---

api/config.go
api/url.go

I've been observing that when using the API library, connections are leaked (see https://github.com/cloudfoundry-community/shield_exporter/issues/3). This PR fixes this by:
* SecureBackendURI function reads (and discards) the ping requests to avoid leaking (`ESTABLISHED`) connections
* Disable Keep Alives, as connections are not reused
* Set a connection timeout
* If environment has Proxy settings, use them when setting up the connection

Fix API library leaking connections

---

cmd/shield/command.go
cmd/shield/main.go
cmd/shield/raw.go

Examples:
shield store gcp-store --uuid
85727ac0-1966-4a98-9bbe-4508dcb13820
shield schedule daily --uuid
6b24e53e-aaa8-459f-ba96-3ad6bd609a56
This will allow script to go from:
```
targ=$(shield --raw target   $name     | jq -r '.uuid // empty')
stor=$(shield --raw store    gcp-store | jq -r '.uuid // empty')
retn=$(shield --raw policy   one-day   | jq -r '.uuid // empty')
sche=$(shield --raw schedule daily     | jq -r '.uuid // empty')
```
To
```
targ=$(shield --uuid target   $name)
stor=$(shield --uuid store    gcp-store)
retn=$(shield --uuid policy   one-day)
sche=$(shield --uuid schedule daily)
```

--uuid flag will display only UUID of a target/store/policy/schedule/job

---

cmd/shield/command.go
cmd/shield/finder.go
cmd/shield/main.go

`create-store`/`create-target`/`create-schedule`/`create-policy` commands now support an `--update-if-exists` flag which will find the first item by name and updated it; rather than create a duplicate.
Example:
cat <<EOF | shield --raw --update-if-exists create-schedule
{
"name":"daily",
"when":"daily 3am"
}
EOF

create-* actions have --update-if-exists flag

---

Makefile
plugin/consul-snapshot/plugin.go
plugin/consul/plugin.go

Since Consul 0.7.1 the command `consul snapshot` has been available to backup and restore all of Consuls entities to a local file.
This PR updates the consul plugin to make use of the native consul snapshot command for backup and restore.

Update consul plugin to use consul-snapshot

---

bin/dev-setup
cmd/shield/commands/access/init.go
cmd/shield/commands/access/prompt.go
cmd/shield/commands/access/unlock.go

Pulled the prompting logic out of safe to do a no-echo, double-entry TUI flow for shield unlock and init commands. Updated devsetup to use expect to handle the new init and unlock prompts.

Added secure password entry for unlock and init commands

---

api/backend.go
api/url.go
cmd/shield/commands/backends/create.go
cmd/shield/commands/backends/list.go
cmd/shield/commands/backends/utils.go
cmd/shield/commands/command.go
cmd/shield/commands/options.go
cmd/shield/config/config.go
cmd/shield/config/dirty_test.go
cmd/shield/main.go

#278 
--ca-cert is now implemented. It specifies a root CA to trust. If given during `create-backend`, that backend will always use it.
If used otherwise, it will override whatever the backend setting is.
The flag takes a value. If the value is a PEM encoded cert, it will use it directly. If its not, it will be interpreted as a file path which should contain a PEM encoded cert therein.
Also, in order to see things about the configured certs, `backends --full` has been implemented. It shows more verbose info about the configured backends, including the auth token and the ca-cert. The ca-cert column shows the plaintext subject, SANs, and validity time range.

Cli ca cert

---

api/status.go
cmd/shield/commands/options.go
cmd/shield/main.go
core/api.go

* API Version is output from daemon API as an int in the JSON response of
/v1/health
* API library can receive version int
* CLI checks on startup what the version is. No version return implies
version 1. Otherwise, use what is returned. Errors if server can't be
reached, handing the error back to the user.

Can detect API version

---

api/curl.go
cmd/shield/commands/dispatcher.go
cmd/shield/commands/misc/curl.go
cmd/shield/main.go

This new command allows operators and SHIELD hackers to interact
directly with the SHIELD API, without interpreting the JSON result.
Responses from the SHIELD API will be printed, with some formatting.
Example:
$ shield curl /v2/health
$ shield curl POST /v2/tenants/create <tenant.json

New `shield curl` command

---

core/v2.go
db/agents.go

Pulled out metadata from /v2/agents to reduce info spam
Added a /v2/agents/:uuid API to request more verbose agent info (i.e. metadata)
Improved formatting of metadata such that it is returned as actual json for easier parsing

Updated Agents API

---

bin/testdev
core/auth.go
core/config.go
core/github_auth.go
core/token_auth.go
core/uaa_auth.go
core/v2.go
web2/htdocs/index.html

This commit introduces a new authentication provider for doing Token
Authentication via the CLI.  It also introduces a split in how auth
providers are listed, so that admins can configure certain auth
providers to only work via the Web UI or the CLI.

Token Authentication Provider

---

api/access.go
api/backend.go
api/errors.go
api/status.go
api/url.go
bin/testdev
cmd/shield/commands/access/login.go
cmd/shield/commands/access/logout.go
cmd/shield/commands/access/whoami.go
cmd/shield/config/config.go
cmd/shield/config/manip_test.go
cmd/shield/main.go
core/api.go
core/config.go
core/core.go
core/debug.go
core/v2.go

* Auth prompting was taken out of the api package and moved into CLI
commands. A user now needs to authenticate manually with one of these
commands, as opposed to the old way, in which the user would simply be
prompted upon receiving a 401
* API functions were added for contacting POST /v2/auth/login, GET
/v2/auth/logout, and GET /v2/auth/id.
* Parsing functions for getting v1 and v2 API error responses were
added. v1 endpoints on v2 APIs will currently be unable to get error
messages, but this will be okay once the v1 endpoints go away.
* Error types were added for 401s and 403s, namely ErrUnauthorized and
ErrForbidden. These can be type checked to determine if an api error was
due to authentication problems.
* The core API exposes test endpoints if the debug flag in the daemon
config is …

CLI added login, logout, and whoami

---

core/v2.go
route/error.go
route/request.go
route/route.go

The new v8 route framework will now issue additional diagnostic message
to API callers when something fails, server-side, if the SHIELD Core
is running in `debug` mode.
Instead of just this:
{
"error": "Something went horribly wrong"
}
API consumers will get this (again, only in `debug` mode):
{
"error": "Something went horribly wrong",
"diagnostic": "server-side error: sql: expected 8 arguments, got 6"
}
Initially, we did not propagate the exact errors to the front-ends to
avoid issues relating to information disclosure.  However, since we do
not advice (nor support) running production SHIELD Cores in debug mode,
this is not a concern in this case.
What this does net us is additional speed in UI / CLI development, since
we can view the errors that are normally only logged server-side, …

Provide Diagnostic Messages via API, in debug mode

---

api/tenants.go
cmd/shield-umc/finders.go
cmd/shield-umc/main.go
cmd/shield/commands/dispatcher.go
cmd/shield/commands/tenants/banish.go
cmd/shield/commands/tenants/create.go
cmd/shield/commands/tenants/delete.go
cmd/shield/commands/tenants/edit.go
cmd/shield/commands/tenants/get.go
cmd/shield/commands/tenants/invite.go
cmd/shield/commands/tenants/list.go
cmd/shield/main.go
core/v2.go
db/tenants.go
t/api

you can now list, create, edit, and delete tenants, as well as invite and banish users to and from tenants from the SHIELD CLI.  The CRUD functionality of CLI tenancy is tested and proven in t/api, but the invite and banish functionality is untested in t/api as of now.

Added CLI support for tenancy functionality

---

core/v2.go
db/retention.go

when a tenant is created via cli or web ui/api, the newly created tenant will inherit all of the global templated retention policies created by the site admin.

Inherit global retention policies when creating a tenant

---

agent/agent.go
agent/command.go
bin/shield-pipe
core/core.go
core/health.go
core/storage.go
db/schema_v4.go
db/stores.go
db/targets.go
db/tasks.go
db/tasks_test.go

SHIELD core now checks cloud stores periodically, and updates the stores db table with the health status of the store, and the id of the most recent health test that was ran against it.  If any of the stores fail the health check test (read from store, write to store, compare written bits and read bits for miswrites) the store will be updated with a failing health field in the db, and the web UI will display to the user that the cloud storage is failing.

added cloud store health checks to core

---

core/v2.go

Archive deletion now purges the data from the store, but keeps the metadata in the DB.

Updated "Delete Archive" semantics

---

core/core.go

Sqlite is running into locking issues on testdev
Store testing would try to update a store, get a nil obj and segfault
Consider WAL mode (if applicable) to allow concurrent reads and reduce locking instances?

Patched null case in core that caused crash

---

cmd/shield/help/update-job

This should fix #390 
I was not able to verify the change since my local `go` setup seems quite broken and I did not had the time yet to fix that. :(

Fix #390. Update help for update-job with pointing at pause|unpause-job

---

.gitignore
client/v2/shield/tasks.go
cmd/shield/main.go
cmd/shield/utils.go
core/v2.go
db/tasks.go
web2/htdocs/index.html
web2/htdocs/shield.js

This PR adds pagination support for task API requests, as well as hard-limiting the amount of tasks per request. The webui and cli have both been given functionality to support this change, as is follows:
From now on, requests to `/v2/tenants/<UUID>/systems/<UUID>` (and other task-related API calls) will return a soft-limit of 30 tasks. Due to schema limitations, the API may return more than 30 tasks if the last task of the request shares a non-unique `requested_at` timestamp.
To offset API requests, the `?before=<int>` query string can be appended to the API request to get the next 30 tasks that occurred exclusively before `<int>` in chronologically descending order.
A button has been added to the bottom of task pages to allow loading older tasks. 
CLI now has a new `--before` modifier …

Add task pagination to API

---

agent/command.go
bin/shield-pipe
bin/testdev
core/agent.go
core/config.go
core/core.go
core/v2.go
db/tasks.go
plugin/fs/plugin.go
t/api
web2/htdocs/index.html
web2/htdocs/shield.css
web2/htdocs/shield.js

When an operator starts a fresh SHIELD instance (in the case of catastrophic failure, etc.) a new initialization screen is displayed that allows the upload of a previous SHIELD self-backup. An out-of-band restore task is fired, and then shield returns to the login screen.
A few caveats to note: this screen replaces the default initialization page. This means in the case of Vault being blown away, but SHIELD has not been touched, the user is still given the option to restore from a previous SHIELD state (though they can simply just enter a new master password in and be given a fixed key as per previous logic)
This task assumes that SHIELD data is located in `/var/vcap/store/shield/`. It was assumed the use-case of SHIELD would be in a BOSH release.
The ability for the FS plugin to …

Add the ability to restore from previous SHIELD on initialization

---

core/v2.go
web2/htdocs/index.html
web2/htdocs/shield.css
web2/htdocs/shield.js

Because Golang lacks a native ability for error types, the only method within SHIELD right now to differentiate errors is through substring matching. The `/v2/unlock/` endpoint now checks the error it receives when unlocking Vault and if it's an "incorrect password" error, properly throws back a 403 to the client so we can properly determine the error client side.

Fix "something broke" bug when inputting incorrect master password

---

web2/htdocs/index.html
web2/htdocs/shield.js

Currently, when the backend is unable to get the status of certain services (e.g. Vault), the endpoint throws a 500 and the web UI fails to render (it's expecting a proper health response).
There's a lot of different ways to fix this, including revamping the health check to throw specific "core" modes (e.g. "vault_down") to pass to the API, but that's a rabbit hole and maybe not worth much in the eyes of an operator. Monit should typically bring vault right back up, so we just want a transient error for the minute in case an operator checks during that exact window.
This solution introduces a hard-coded "ERRORED" state on a 500 response. It sets all health values to false and empty data storage arrays. It's designed to inform the operator that SHIELD is not in a good state, but avoids …

Add "Errored" state when `/v2/health` throws an error

---

plugin/xtrabackup/plugin.go
t/plugins

This will add the possibility to configure the path to the mysql socket in the xtrabackup plugin.
Without it xtrabackup might not find the running mysql process and cannot perform the backup, if the socket is in an unexpected location.
signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>

add mysql socket to xtrabackup configuration options

---

core/v2.go
db/jobs.go

Bug in requesting ad-hoc backups always showed that the store was
unhealthy.  This was due to the API call not containing the store
health, so it was added.

Added the store health to systems api response

---

bin/testdev

After attempting to run the testdev environment I found nginx was
stalling on a few variables most notably temp paths for compiled in
modules, as I'm running locally on a Linux devbox I figured I would put
the effort in to get nginx to run without issue.

Fix nginx testdev configuration

---

core/api.go
core/auth.go
core/v2.go
util/util.go
web2/htdocs/index.html

- Remote IP is now handled if X-Forwarded-For is set.  The BOSH release
should be setting this via standard nginx configuration.
- The "Created At" column is no longer displayed as an epoch timestamp.
We now strftime() it for human operators to read and comprehend.
Fixes https://trello.com/c/npjxfcIO/59-all-session-ips-showing-as-localhost

Fix up Session Details

---

web2/htdocs/index.html
web2/htdocs/shield.js
web2/src/js/shield.js

500s received from POSTS to /v2/unlock were not handled, resulting in no feedback to the user.  This provides an `.error` span to received the feedback.

Fix handling 500s on unlock API

---

demo/aegis/Dockerfile

`make demo` broken, need to add `ppa:ondrej/php` in order to make it work on `agegis Dockerfile`

Added software-properties-common in order to install php on aegis

---

client/v2/shield/info.go
client/v2/shield/status.go
cmd/shield/main.go
core/api.go
core/info.go
core/v2.go
docs/API.md
docs/API.yml

This PR updates the /v2/info and /v2/health endpoints, stabilizing version population and removing FQDN.  It also updates the shield cli and client library to convey the information to the end user more reliably.

Improve info and health endpoints

---

core/v2.go
db/tasks.go
plugin/bbr-director/plugin.go
route/request.go

tackles https://github.com/starkandwayne/shield/issues/418
For simplicity allows a time string for example:
/v2/tenants/2d8b8052-a004-4f42-aaa5-3c0d67ac3225/tasks?started_at_after=1m30s"
This will show tasks started from server time - 90 seconds (1m 30s)
Same applies for stopped_at_after:
/v2/tenants/2d8b8052-a004-4f42-aaa5-3c0d67ac3225/tasks?stopped_at_after=300s"
Will get all stoped tasks from server time  - 300 seconds

Added started_at_after && stopped_at_after

---

.gitignore
Makefile
agent/command.go
agent/test/bin/shield-report
bin/shield-pipe
client/v2/shield/archives.go
client/v2/shield/targets.go
cmd/shield-report/main.go
cmd/shield/main.go
core/agent.go
core/compression.go
core/core.go
core/v2.go
db/archives.go
db/archives_test.go
db/jobs.go
db/schema.go
db/schema_test.go
db/schema_v5.go
db/targets.go
db/tasks.go
db/tasks_test.go
docs/API.md
docs/API.yml
t/travis
web2/htdocs/index.html
web2/htdocs/shield.css
web2/htdocs/shield.js
web2/src/js/shield.js

Compression is now optional, and can be set on a per-target basis.

Make Compression Optional

---

web2/htdocs/index.html

Fixes https://trello.com/c/8dRQFKmB/79-confusing-use-of-labels-on-backups-and-restores

Only show tags on non-backup tasks (purge, restore, etc.)

---

plugin/mysql/plugin.go

allows using option `mysql_database`

fix mysql plugin to accept database name when restoring

---

cmd/shield/main.go

Currently, when viewing a target in the shield CLI, it does not give any information about the configuration for said target. This PR adds a `Configuration` line to the output of `target` and `update-target` to show the operator the current or the updated configuration without having to run `targets`

Update outputs from 'shield target' and shield update-target'

---

plugin/webdav/plugin.go

The WebDAV RFC (4918) does not strictly require conforming
implementations to auto-vivify intervening directories.  Nginx
apparently does this; Apache2 does not.
Now, the `webdav` plugin will create the intervening directories,
expecting either a 201 Created, or a 405 (directory component exists).
Fixes #463

Issue MKCOL (mkdir) requests in webdav

---

Makefile

using test's bin shield-report to output the execution result
address the issue of #475

fix agent tests failue #475

---

ci/release_notes.md
plugin/postgres/plugin.go

This pr adds the functionality of adding optional flags to the pg_dump command of the postgres plugin. 
This is to fix #478 and #483

update postgres plugin to allow optional flags

---

web/htdocs/index.html

The name field wasn't being populated, so it was appearing to not have a
value to the validation code. This meant any plugin using an enum for
its options could not be filled out on the web UI.

Fix enum forms in web ui wizards

---

bin/shield-pipe

As a jerk who has GNU find first in his PATH on his Macbook,
I would like the shield-agent to be able to find plugins in the testdev environment
Fix enclosed
*rings gong*

Support GNU find on Darwin

---

ci/release_notes.md
db/agents.go
db/schema.go
db/schema_v9.go
web/htdocs/index.html
web/htdocs/js/shield.js

Fixes #526
SHIELD now tracks when it last checked each agent separately
from when it last "saw" the agent.  _Last Seen_ now means the
point in time when the agent last connected to the SHIELD core,
and _Last Checked_ is when the core last connected to the agent
for metadata retrieval.
SHIELD now allows agents to change their IP address; only the
agent name is unchangeable.  Previously, attempts to change an
agents registered IP address (without changing its name) would
fail.
The "Agents of SHIELD" admin page no longer gets stuck in a
loading loop whenever websocket events are seen.

Allow Agents to change their IP addresses

---

ci/release_notes.md
web/htdocs/js/shield.js

Global Storage Configuration details are now properly loaded
when accessing a global store detail page from the admin panel.
Previously, the details would only load if you visited the
global store from the "Storage Systems" (non-admin) top-level,
which only works if you actually have a tenant.
Fixes #535.

Load Global Store Details for Admins

---

ci/release_notes.md
core/api_v2.go
web/htdocs/index.html
web/htdocs/js/shield.js
web/htdocs/shield.css

The web UI for rekeying SHIELD Core now correctly identifies
when the operator would like to rotate the fixed key.  Also, the
error messaging for an incorrect _current_ master password is
better now, and by default, the "rotate fixed key" checkbox on
the rekeying form is off.
Fixes #546.

Handle Fixed Key Rotation in Rekey Web UI

---

plugin/s3/plugin.go

A 301 response without a Location header is an error per the HTTP RFCs.
But Amazon returns a 301 without a Location header precisely for what it
calls the PermanentRedirect error code.  This is used, during path-based
addressing to point to a bucket outside of the US regions.
This commit causes the s3 plugin to re-attempt actions when the returned
response violates this part of the HTTP speec, and re-attempt without
path-based addressing.
Fixes #568

Handle AWS 301's without Location: headers

---

agent/ping.go
ci/release_notes.md
cmd/shield/main.go

The SHIELD Agent and the SHIELD CLI now trust System Root CAs, so if
your infrastructure uses publicly-verifiable certificates (or if you are
running your own CA, with support for it on all hosts) you should have a
better time with X.509 certificate verification.
Fixes #555 and #556.

Trust System CAs

---

cmd/shield/main.go

Switching `annotate-archive` to use the fuzzy matching of FindArchive.
This fixes #571.

Allow annotate-archive to take short uuids arguments

---

db/archives.go

Previous when deleting a target with active archives via the cli, the web ui would log out a user and prevent them from logging in. We should now have no issue with /v2/bearings querying for archives that joins on a null job. This should fix #565.

fix for bug with not being able to log in after deleting target

---

web/htdocs/shield.css

Make bottom margin of data system card in web UI less, so that I can no longer fit other imaginary cards inside of the space between cards. Now I can see more cards per screen (CPS). CPS++

Remove extra bottom margin from data system card

---

db/agents.go
db/archives.go
db/archives_test.go
db/db.go
db/db_test.go
db/fixup.go
db/jobs.go
db/memberships.go
db/schema.go
db/schema_test.go
db/schema_v1.go
db/schema_v2.go
db/schema_v3.go
db/schema_v4.go
db/schema_v5.go
db/schema_v6.go
db/schema_v7.go
db/schema_v8.go
db/schema_v9.go
db/sessions.go
db/stores.go
db/targets.go
db/tasks.go
db/tasks_test.go
db/tenant_test.go
db/tenants.go
db/tokens.go
db/users.go
plugin/mongo/plugin.go

We had race conditions in the db layer! no longer! The lock grabbing is moved up an abstraction layer. It is very ugly now - this is an increase in both functionality and ugliness in equal measure.
This fixes:
* Issues where row iterations would hold the read lock on the database without holding the SHIELD db layer Mutex.
* Issues where sequences of queries that should be transactional were effectively not being the lock was being taken, released, and then taken again.
As I was going through the db tests, there are also a few lines where errors were not being checked. Now they're being checked. Hooray.

db locking

---

db/fixup.go

Now, we log the errors we encounter while trying to apply fixups, so
that both operators and SHIELD developers can better troubleshoot
issues.

Log DB errors in Fixups code

---

db/db.go
db/fixup.go

We now only run the fixups once (although the code does allow re-runs,
should we ever plumb in an API / UI for this).

More Rigorous Fixup Handling

---

core/api_v2.go
core/bus/bus.go
core/bus/debug.go
core/core.go
core/main.go
route/websockets.go

Mbus channels have a buffer size - if a message is attempted to be put
in a full queue, the channel will be closed and the slot deregistered.
The buffer size is configurable as "slot-size". Additionally, the number
of slots that are initialized is now configurable as "max-slots".
Mbus event sends are asynchronous now. Calls to SendEvent should now
return in a predictable amount of time instead of potentially needing to
wait for a message to be read from a channel synchronisly.
The mbus/status endpoint has been altered: it only lists the slots that
are active at that moment (to avoid dumping 2047 empty slots, for
example). Each slot reports its current channel len and high watermark
channel length now. The status also reports the configuration of the
mbus as a whole.
Register now returns a …

Mbus queues are buffered; sending events is async

---

agent/config.go
bin/testdev
cmd/shield-agent/main.go
cmd/shieldd/main.go
core/api_v1.go
core/core.go
core/main.go
init/core

This changeset allows the SHIELD Core (shieldd) and the SHIELD Agent
(shield-agent) to be configured completely (minus auth providers) via
environment variables.  This is all but required for running SHIELD
effectively in Docker, Docker Compose, and Kubernetes.
To do so, I also had to incorporate changes requested in #618, to remove
the variable-length `fabrics:` configuration.
`bin/testdev` has been updated to incorporate an environment-first
approach, as a proof-of-concept.
Fixes #618.

Environmental Configuration of SHIELD

---

db/tasks.go

When creating the task record for a restore, we were not properly
propagating the compression field of the archive to the task; this meant
that if you were not compressing your backups, the restore operations
would fail (because it tried to bunzip2 the uncompressed stream).
Fixes #622

Fix Restore of Uncompressed Backups

---

db/archives.go
web/htdocs/index.html

When an archive is purged. It updates the count in the data systems page and removes the archive from the list of valid archives without reloading the page. Fixes #617

Archive status updates in real time when an archive is purged

---

bin/testdev
core/core.go
core/duration.go
core/main.go
db/archives.go
db/tasks.go
db/utils_test.go
vendor/github.com/jhunt/go-envirotron/LICENSE
vendor/github.com/jhunt/go-envirotron/README.md
vendor/github.com/jhunt/go-envirotron/envirotron.go
vendor/vendor.json

This change introduces new retention lifetimes for purged archives
(which have already been removed from the underlying cloud storage)
and task log contents.
Fixes #589

Purge old task logs / archives

---

core/main.go

v.status was never returning "unsealed". Fixed the conditional statement.

Vault status

---

web/htdocs/js/lib.js

Previously, if the daily storage increase in the web UI was negative,
then it would always display the amount in bytes, no matter how large
the number becomes. This should allow the unit formatting to work even
when the number is negative.

Daily Storage Increase can use larger units

---

core/api_v2.go

Attempting to cancel a task by DELETEing at the tenant specific task API
endpoint would result in No Such Task being returned. It appears that
this is because of a reversed logic check, which prevents this endpoint
from being a workaround to delete global tasks. Instead, it ONLY allows
the cancellation of global tasks.
Addresses #647

Reverse Global Tenant check logic in cancel task endpoint

---

web/htdocs/js/data.js

Previously, it just returns the first agent in the hash. 
Fixes #660

Make AEGIS.agent return the requested agent

---

db/schema_v11.go

When upgrading from 8.5.0 -> 8.6.0 failed it left the jobs_new table in the database. This patch checks if the jobs_new table exists and if it already exists drops the table and the rest of the migrating to schema_v11 continues.

Fixed jobs_new table already exists when upgrading to v_11

---

web/htdocs/index.html
web/htdocs/js/data.js
web/test/tests.js

The storage footprint on each data system page in the web ui was counting purged archives. This PR adds the ability to filter archive retrieval from AEGIS by purged-ness or purged-less-ness. The storage footprint template then uses this to only count archives that SHIELD is aware are still impacting the storage footprint.
The archive retrieval code has gained a few more test specs related to filtering by purged-ness.
Fixes #658

Storage footprint

---

db/jobs.go
db/schema_v12.go
db/targets.go

Don't segfault if the job can't be found. Don't return no error if you
can't list jobs. Return consistent errors for setting job and target
health.

Report errors better in v12 migration.

---

web/htdocs/index.html
web/htdocs/js/shield.js

Added new button to the Web-UI to delete agents. Should fix #641

Web-UI delete agents button

---

ci/release_notes.md
plugin/metashield/plugin.go

Adding two additional but optional fields to allow the meta shield plugin to properly target a shield with tls. 
Previously you could only use the plugin using the agent colocated on the SHIELD box and targetting shieldd on loopback. Now you can specify the SHIELD core CA cert as well as skip ssl validation when configuring a shield backup.

Metashield tls

---

web/htdocs/js/data.js

When shield is fronted by a reverse proxy which hides the 401 authentication status to the websocket handshake and rather returns a `HTTP/1.1 101 Switching Protocols` response (see https://github.com/spring-cloud/spring-cloud-gateway/issues/1884 and https://stackoverflow.com/questions/63196638/spring-cloud-gateway-hides-server-websocket-handshake-401-failures-to-clients), then shield client code enters an infinite loop of requests to `v2/events` and `v2/bearings`.
This comes from the fact that the error handling code to the 401 response status (which redirects the browser to the homepage) does not trigger. Instead, the websocket open event triggers a `v2/bearings` ajax call whose handler fails to parse the following unauthorized response with the following trace
```json …
```

Fix for infinite loop through misbehaving WebSocket proxies

---

Dockerfile
Makefile
plugin/gspt.go
web/htdocs/index.html

This adds functionality to shield to build native arm64 binaries and updates the shield UI to point to both intel and arm64 binaries.

Adding Mac ARM64 functionality to shield

---

plugin/rabbitmq-broker/plugin.go

Renamed the RabbitMQ Broker Backup Plugin to remove 'Pivotal' from it. And added a forward slash truncate for the RabbitMQ dashboard url  user input when applicable.

Renamed RabbitMQ Plugin and added / trim

---

ci/release_notes.md

Bug fix for the login screen of Shield not showing Github OAuth button.

Added releases notes for the bug fix- Login screen in Github OAuth

---

ci/release_notes.md
cmd/shield/help.go
cmd/shield/main.go
core/api_v2.go
db/schema_test.go

To use import endpoint, shield's curl's body input using stdin has issues with using escape characters. This improvement will enable the user to provide a filename from which the request body will be supplied.

Adding --file flag for shield curl
